version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - automations
  - caseta
  - codez
  - dominikmicuta
  - esmodules
  - execa
  - fastify
  - gotify
  - grocy
  - hacs
  - haos
  - hass
  - hassio
  - keymap
  - keyof
  - lutron
  - nestjs
  - pico
  - pino
  - quickboot
  - quickstart
  - skynet
  - swappable
  - takken
  - tldr
  - tsdoc
  - typeof
  - wago
  - webber
  - webbertakken
ignoreWords: []
import: []
