version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - codez
  - webbertakken
  - webber
  - takken
  - hass
  - quickstart
  - grocy
  - fastify
  - hacs
  - pino
  - dominikmicuta
  - wago
  - keyof
  - quickboot
  - execa
  - keymap
  - lutron
  - pico
  - swappable
  - caseta
  - hassio
  - tsdoc
  - tldr
  - gotify
  - typeof
  - nestjs
ignoreWords: []
import: []
